---
abstract: 'Calculate password strength'
author:
  - 'Oleg Alistratov <zero@cpan.org>'
build_requires:
  Encode: 0
  POSIX: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Password-Entropy
provides:
  Data::Password::Entropy:
    file: lib/Data/Password/Entropy.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
