---
abstract: 'Calculate password strength'
author:
  - 'Oleg Alistratov <zero@cpan.org>'
build_requires:
  Encode: 0
  POSIX: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Password-Entropy
provides:
  Data::Password::Entropy:
    file: lib/Data/Password/Entropy.pm
    version: 0.06
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: http://github.com/alien/ali-public/tree/master/modules/Data-Password-Entropy/
version: 0.06
